---
config:
  layout: elk
---
classDiagram
direction LR
    class Board {
	    players: list[Players]
	    tile_bag: list[Tile]
	    word_list: WordList
	    board: list
	    turn: int
	    is_first_move: bool
	    current_player: Player
	    is_game_over: bool
	    consecutive_passes: int
	    \__post_init__()
	    initialize()
	    make_move()
	    next_turn()
	    is_contigous()
	    touches_existing_tile()
	    extract_words()
	    _scan()
	    to_save_dict()
	    from_save_dict()
	    serialize()
	    save_to_redis()
	    load_from_redis()
	    score_word()
	    check_game_over()
	    do_game_over()
	    finalize_scores()
    }
    class Player {
	    word_bank: list[TileBank]
	    score: int
    }
    class TileBank {
	    hand: list[Tile]
	    get_new_hand()
	    remove_tiles()
	    \__contains__()
    }
    class Tile {
	    letter: str
	    points: int
	    multiplier: int
	    x: int
	    y: int
	    is_blank: bool
	    \__eq__()
	    \__hash__()
	    from_another()
    }
    class WordList {
	    word_list: set(str)
	    load_word_list()
	    is_valid_word()
    }
    Board *-- Player : Board.player
    Player *-- TileBank : Player.word_bank
    TileBank *-- Tile : TileBank.hand
    Board *-- Tile : Board.tile_bag
    Board *-- Tile : Board.board
    Board *-- WordList : Board.word_list
